### ISSUE TITLE
'libexslt/libexslt.h' file not found

### ISSUE THREAD

**Issue by ghost** [Blue-Rocket/BRCybertron#2]
Hi, I'm trying to get your lib up and running in my Swift project. I added it through cocoapods, but during build, this error is thrown:

.../Pods/BRCybertron/libxslt/libexslt/common.c:2:10: 'libexslt/libexslt.h' file not found

Any idea about the reason and a solution?

**Comment by msqr** [comment]
Hello, sorry I missed your post way back when. I'm afraid I don't have any suggestions for you, I haven't been working with this project in Swift. I'll close this issue now; hopefully you found a solution!

**Comment by Noroxs** [comment]
Short answer: 
You have to modify the `header search paths` within your target build settings. They have to contain the following paths:
`${PODS_ROOT}/BRCybertron/BRCybertron/libxslt`
`${PODS_ROOT}/BRCybertron/libxslt`
I changed it directly for the BRCybertron target within the pod project.
Maybe you have to clean your build folder and DerivedData.

Long answer:
Swift doesn't support `Cocoa Touch Static Libraries` for this reason you add the flag `use_frameworks!` to your pod file ([Why do we use use_frameworks in CocoaPods?](https://stackoverflow.com/a/41210375/4243514)). This will add the libraries as `Cocoa Touch Frameworks`. This will change the structure of your Pods directory. The `../Pods/Headers/Private` directory will not contain any header files anymore. The files will be added directly to the `../Pods/BRCybertron` directory. This is the reason why your project can't find the files. You have to modify the `header search paths` within your target build settings.

There are two solutions for this:
1. Manually change the header search paths (you have to do this every time you perform a pod update)
1.1 Select the `Pods` project within your `*.xcworkspace`
1.2 Select the target `BRCybertron`
1.3 Select `Build Settings` tab
1.4 Go to `Header Search Paths` section
1.5 Add the following lines:
`${PODS_ROOT}/BRCybertron/BRCybertron/libxslt`
`${PODS_ROOT}/BRCybertron/libxslt`
1.6 Clean Build folder + DerivedData
2. Adjust the `HEADER_SEARCH_PATHS` for the `BRCybertron.podspec`
2.1 Create a fork of this project
2.2 Add the following lines to the `'HEADER_SEARCH_PATHS' => ...` section:
`${PODS_ROOT}/BRCybertron/BRCybertron/libxslt`
`${PODS_ROOT}/BRCybertron/libxslt`
2.3 Change your podfile to use your fork `pod 'BRCybertron', :git => 'https://github.com/{Your_User}/BRCybertron.git'`
2.4 Perform `pod update` 

I use it for an Objective-C project that contains Swift so I can't guarantee that this will work.
